"""
STEP 1 of the framework: Prove U = Z/DZ (unrestricted sumset is full).

Each A_j = 3^{k-1-j} * {2^0, 2^1, ..., 2^{p-1}} mod D.
Since gcd(3^{k-1-j}, D) = 1, A_j = 3^{k-1-j} * H where H = <2> in (Z/DZ)*.

The unrestricted sumset is U = A_0 + A_1 + ... + A_{k-1}.

If H = (Z/DZ)*, then each A_j = (Z/DZ)* (or a coset), and k ≥ 2 sums
of the full group easily cover Z/DZ.

More generally: H is the cyclic subgroup generated by 2 in (Z/DZ)*.
|H| = ord_D(2) = L.

A_j is the coset 3^{k-1-j} * H. In the quotient group G = (Z/DZ)*/H,
the cosets map to elements g_j = [3^{k-1-j}] = [3]^{k-1-j}.

The unrestricted sumset U restricted to units is:
U ∩ (Z/DZ)* = sumset of cosets g_0*H + g_1*H + ... + g_{k-1}*H.

Within each coset, we can reach all L elements (since H is a full geometric
progression of length L = ord_D(2), and L ≤ p but the sumset of multiple
copies of H might be larger).

Actually: A_j contains p elements of Z/DZ (the values 3^{k-1-j}*2^i mod D
for i = 0,...,p-1). If ord_D(2) = L, then these p values have only L
distinct values (since 2^i cycles mod D with period L). So |A_j| = min(p, L).

Case 1: L = p (ord_D(2) = p). Then |A_j| = p elements, all in one coset of H.
Case 2: L < p. Then |A_j| = L < p.

Let's first check what L is for our cases.
"""

from math import comb, log, gcd

def multiplicative_order(a, n):
    if gcd(a, n) != 1:
        return None
    r = 1
    x = a % n
    while x != 1:
        x = (x * a) % n
        r += 1
        if r > n:
            return None
    return r

def euler_phi(n):
    result = n
    p = 2
    temp_n = n
    while p * p <= temp_n:
        if temp_n % p == 0:
            while temp_n % p == 0:
                temp_n //= p
            result -= result // p
        p += 1
    if temp_n > 1:
        result -= result // temp_n
    return result

def analyze_group_structure(p, k):
    D = 2**p - 3**k
    if D <= 0:
        return

    L = multiplicative_order(2, D)
    ord3 = multiplicative_order(3, D)
    phi = euler_phi(D)

    # The subgroup <2,3> in (Z/DZ)*
    # Its order divides phi(D), and it contains both <2> and <3>
    # The order of <2,3> = lcm(ord(2), ord(3)) IF 2 and 3 generate
    # independent cyclic groups. But they might not.
    # Actually |<2,3>| = |<2>| * |<3>| / |<2> ∩ <3>|... not exactly.
    # Let's just compute it.

    subgroup = set()
    for a in range(L + 1):
        for b in range(ord3 + 1):
            val = pow(2, a, D) * pow(3, b, D) % D
            subgroup.add(val)
    subgroup_size = len(subgroup)

    # Number of cosets of H = <2> used by A_j
    # A_j is the coset 3^{k-1-j} * H. The distinct cosets are determined
    # by the values 3^m mod D for m = 0,...,k-1 in the quotient (Z/DZ)*/H.
    coset_reps = set()
    for j in range(k):
        # A_j uses the coset 3^{k-1-j} * H
        # In the quotient, this is [3^{k-1-j}] = [3]^{k-1-j}
        rep = pow(3, k-1-j, D)
        # Find which coset of H this belongs to
        # Two values are in the same coset if their ratio is in H = <2>
        coset_reps.add(rep)  # Simplified; proper coset analysis below

    # Proper coset analysis: two values a, b are in the same H-coset
    # iff a/b ∈ H, i.e., a * b^{-1} is a power of 2 mod D.
    # Check which weight coefficients 3^m give the same coset
    cosets_used = {}
    for j in range(k):
        coeff = pow(3, k-1-j, D)
        # Find coset: coeff = 2^t * (representative) for some t
        # Actually, find the coset by checking if coeff * 2^{-s} ≡ coeff' for any s
        found = False
        for c_id, c_rep in cosets_used.items():
            ratio = (coeff * pow(c_rep, D-2, D)) % D  # coeff / c_rep mod D
            # Check if ratio ∈ H = <2>
            if ratio in {pow(2, t, D) for t in range(L)}:
                found = True
                break
        if not found:
            cosets_used[len(cosets_used)] = coeff

    num_cosets = len(cosets_used)

    print(f"\n(p,k)=({p},{k}): D={D}")
    print(f"  phi(D) = {phi}")
    print(f"  ord_D(2) = L = {L}")
    print(f"  ord_D(3) = {ord3}")
    print(f"  |<2,3>| = {subgroup_size}")
    print(f"  p = {p}, L = {L}, p/L = {p/L:.2f}")
    print(f"  Distinct cosets of <2> used by weight classes: {num_cosets}/{k}")

    # KEY THEOREM ATTEMPT:
    # If |A_j| = L for each j, and we sum k copies from possibly different cosets,
    # the sumset has size ≥ min(D, k*L) by Cauchy-Davenport (for prime D).
    # For D prime: |A+B| ≥ min(D, |A|+|B|-1).
    # So |U| ≥ min(D, k*L - (k-1)) = min(D, k*L - k + 1).
    # For this to be D: need k*L ≥ D + k - 1, i.e., L ≥ (D+k-1)/k ≈ D/k.

    cauchy_davenport_bound = min(D, k * L - k + 1) if D > 0 else 0

    # For D prime, Cauchy-Davenport gives:
    is_prime = all(D % i != 0 for i in range(2, min(D, 10000)))
    if is_prime and D > 1:
        print(f"  D is prime!")
        print(f"  Cauchy-Davenport bound: |U| ≥ min(D, k*L - k + 1) = {cauchy_davenport_bound}")
        if cauchy_davenport_bound >= D:
            print(f"  >>> Cauchy-Davenport PROVES U = Z/DZ! <<<")
        else:
            print(f"  Cauchy-Davenport gives {cauchy_davenport_bound}/{D}")
    else:
        print(f"  D is composite")
        # For composite D, use Kneser's theorem instead
        print(f"  Kneser bound (approximate): |U| ≥ min(D, k*L/{num_cosets})")

    # Additional: when do ALL A_j coincide (same coset)?
    if num_cosets == 1:
        print(f"  All weight classes use THE SAME coset of <2>!")
        print(f"  This means 3 ∈ <2> mod D (3 is a power of 2 mod D)")
    elif num_cosets == k:
        print(f"  All weight classes use DIFFERENT cosets of <2>")
    else:
        print(f"  {num_cosets} distinct cosets among {k} weight classes")

    return L, num_cosets


print("="*70)
print("GROUP STRUCTURE ANALYSIS")
print("="*70)

for p in range(5, 25):
    k = round(p * log(2) / log(3))
    if k >= p or k < 1:
        continue
    D = 2**p - 3**k
    if D <= 0:
        continue
    analyze_group_structure(p, k)
