"""
Part 0 Attack: WHY is residue 0 mod D special?

Key question: Among all residues r mod D, residue 0 is never hit by S(I).
What PROPERTY distinguishes r=0 from r=1, r=2, etc.?

If we can identify such a property, it might be the basis for a framework.

Approach:
1. For each residue r, count how many I have S(I) ≡ r mod D.
2. Characterize the "missing" residues (those hit by 0 patterns).
3. Look for number-theoretic properties that separate hit from missed residues.
4. Focus on what makes r=0 special.

DEEPER IDEA: Consider S(I) as a point in (Z/DZ). The set of achievable
residues is A = {S(I) mod D : I}. We want to show 0 ∉ A.

The set A has specific algebraic structure inherited from the generating set:
{3^{k-j} * 2^r mod D : 0 ≤ r ≤ p-1, 0 ≤ j ≤ k-1}

with the constraint that each j appears exactly once (the rank-weight coupling).

NEW APPROACH: Think of S(I) mod D as a SUM IN (Z/DZ)^* (since gcd(S(I), D)
is typically 1). The multiplicative structure of Z/DZ might matter.

Since 2^p ≡ 3^k mod D, the subgroup ⟨2,3⟩ of (Z/DZ)^* is constrained.
In particular, 2^p = 3^k in Z/DZ. This is a SINGLE equation relating 2 and 3.

The terms of S(I) are 3^{k-j} * 2^{i_j}. In (Z/DZ), these are elements of
the subgroup generated by 2 and 3. The sum of k such elements (with the
rank-weight coupling) must be 0 mod D.

But sums in (Z/DZ) don't respect the multiplicative structure — we're mixing
addition and multiplication. This is the fundamental difficulty.

UNLESS: we can find a MULTIPLICATIVE CHARACTER χ such that χ(S(I)) has
a specific value, and χ(0) is different. But χ(0) is undefined for
multiplicative characters (since 0 is not in the multiplicative group).

The Fourier analysis (additive characters) was already done (Theorem 4-5).
What about MULTIPLICATIVE Fourier analysis?

For r ≢ 0 mod D, the multiplicative character χ(r) is well-defined.
For r ≡ 0 mod D, we're outside the group. So the distinction between
r = 0 and r ≠ 0 is precisely the boundary between (Z/DZ)^* and {0}.

This is a NATURAL boundary — and maybe the framework should exploit it.

HYPOTHESIS: There is a function f: (Z/DZ) → R such that:
- f(0) has a specific value (say, f(0) = V)
- For S(I) mod D, f(S(I) mod D) ≠ V for all I
- The proof that f(S(I) mod D) ≠ V uses the structure of S(I)

What could f be? It should be sensitive to the additive-multiplicative
structure of the problem.
"""

from itertools import combinations
from math import comb, log, gcd, sqrt
from collections import Counter, defaultdict

def S_value(I, k):
    I_sorted = sorted(I)
    return sum(3**(k-j-1) * 2**I_sorted[j] for j in range(k))

def multiplicative_order(a, n):
    """Compute ord_n(a)."""
    if gcd(a, n) != 1:
        return None
    r = 1
    x = a % n
    while x != 1:
        x = (x * a) % n
        r += 1
        if r > n:
            return None
    return r

def analyze_residue_zero(p, k):
    """Why is residue 0 mod D never hit?"""
    D = 2**p - 3**k
    if D <= 0:
        return
    C = comb(p, k)

    # Compute all S(I) mod D
    residue_counts = Counter()
    residue_patterns = defaultdict(list)
    for I in combinations(range(p), k):
        s = S_value(I, k)
        r = s % D
        residue_counts[r] += 1
        if len(residue_patterns[r]) < 3:
            residue_patterns[r].append(I)

    hit_residues = set(residue_counts.keys())
    missed_residues = set(range(D)) - hit_residues

    print(f"\n{'='*70}")
    print(f"(p,k) = ({p},{k}): D = {D}, C = {C}")
    print(f"{'='*70}")
    print(f"Hit residues: {len(hit_residues)}/{D}")
    print(f"Missed residues: {len(missed_residues)}/{D}")

    # Property 1: Is 0 the ONLY "special" missed residue, or are others missed too?
    print(f"\nMissed residues: {sorted(missed_residues)[:30]}{'...' if len(missed_residues) > 30 else ''}")

    # Property 2: GCD of missed residues with D
    missed_gcds = Counter()
    for r in missed_residues:
        g = gcd(r, D) if r > 0 else D
        missed_gcds[g] += 1
    hit_gcds = Counter()
    for r in hit_residues:
        g = gcd(r, D) if r > 0 else D
        hit_gcds[g] += 1

    print(f"\nGCD structure:")
    print(f"  Missed residues by gcd(r,D):")
    for g in sorted(missed_gcds.keys()):
        total_with_gcd = sum(1 for r in range(D) if gcd(r, D) == g) if g < D else 1
        print(f"    gcd={g}: {missed_gcds[g]} missed / {total_with_gcd} total")
    print(f"  Hit residues by gcd(r,D):")
    for g in sorted(hit_gcds.keys()):
        total_with_gcd = sum(1 for r in range(D) if gcd(r, D) == g)
        print(f"    gcd={g}: {hit_gcds[g]} hit / {total_with_gcd} total")

    # Property 3: Quadratic residue structure
    # Is 0 mod D a quadratic residue / non-residue? (0 is neither)
    # What about missed non-zero residues?
    if D < 500:  # Only for small D
        qr = set()
        for x in range(1, D):
            if gcd(x, D) == 1:
                qr.add((x*x) % D)

        missed_qr = sum(1 for r in missed_residues if r in qr and r > 0)
        missed_nqr = sum(1 for r in missed_residues if r not in qr and r > 0 and gcd(r,D) == 1)
        total_coprime_missed = sum(1 for r in missed_residues if gcd(r, D) == 1)

        print(f"\n  Quadratic residues mod D: {len(qr)}/{D}")
        print(f"  Missed coprime residues: {total_coprime_missed}")
        print(f"    of which QR: {missed_qr}, NQR: {missed_nqr}")

    # Property 4: Relationship of missed residues to multiplicative orders of 2 and 3
    ord2 = multiplicative_order(2, D)
    ord3 = multiplicative_order(3, D)
    print(f"\n  ord_D(2) = {ord2}")
    print(f"  ord_D(3) = {ord3}")

    # The subgroup generated by 2 and 3 in (Z/DZ)*
    if D < 2000:
        subgroup = set()
        for a in range(200):
            for b in range(200):
                val = pow(2, a, D) * pow(3, b, D) % D
                subgroup.add(val)
        subgroup_size = len(subgroup)
        phi_D = sum(1 for r in range(D) if gcd(r, D) == 1)
        print(f"  |<2,3>| in (Z/DZ)*: {subgroup_size} / {phi_D} = {subgroup_size/phi_D:.4f}")

        # Are missed residues concentrated in specific cosets of <2,3>?
        missed_in_subgroup = sum(1 for r in missed_residues if r in subgroup)
        print(f"  Missed residues in <2,3>: {missed_in_subgroup}/{len(missed_residues)}")

    # Property 5: The ADDITIVE structure — S(I) is a sum of k terms
    # Each term 3^{k-j-1} * 2^{i_j} mod D lives in a specific set.
    # What is this set?
    term_residues = set()
    for j in range(k):
        for i in range(p):
            term = (3**(k-j-1) * pow(2, i, D)) % D
            term_residues.add(term)
    print(f"\n  Distinct term residues: {len(term_residues)}/{D}")

    # Property 6: The SUMSET structure
    # S(I) mod D is a sum of k terms from specific subsets A_1, ..., A_k
    # where A_j = {3^{k-j-1} * 2^i mod D : i in {0,...,p-1}}
    # Each A_j is a geometric progression mod D
    print(f"\n  Geometric progressions (A_j = 3^{{k-j-1}} * <2> mod D):")
    for j in range(min(k, 4)):
        coeff = 3**(k-j-1) % D
        Aj = set()
        for i in range(p):
            Aj.add((coeff * pow(2, i, D)) % D)
        print(f"    j={j}: coeff=3^{k-j-1}={coeff}, |A_j|={len(Aj)}")

    # CRITICAL TEST: What is the sumset A_0 + A_1 + ... + A_{k-1}?
    # If we could show 0 ∉ sumset, that proves no cycles!
    # But we need the RESTRICTED sumset (each position used at most once)
    # Actually the positions are: one element from each {0,...,p-1} but all distinct
    #
    # This IS the problem, but framing it as a sumset problem connects to
    # additive combinatorics (Freiman's theorem, Plunnecke-Ruzsa, etc.)

    return missed_residues

def analyze_sumset_structure(p, k):
    """
    S(I) mod D = sum_{j=0}^{k-1} a_j * 2^{i_j} mod D
    where a_j = 3^{k-1-j} and i_0 < i_1 < ... < i_{k-1} are from {0,...,p-1}.

    This is a RESTRICTED sumset: choose one element from each of k "slices"
    of the geometric progression 2^0, 2^1, ..., 2^{p-1}, weighted by
    the coefficients a_0 > a_1 > ... > a_{k-1}.

    KEY QUESTION: Is there a sumset-theoretic reason why 0 is excluded?
    """
    D = 2**p - 3**k
    if D <= 0:
        return

    print(f"\n{'='*70}")
    print(f"SUMSET ANALYSIS: (p,k) = ({p},{k}), D = {D}")
    print(f"{'='*70}")

    # Compute the k "weighted element sets" A_j
    A = []
    for j in range(k):
        a_j = pow(3, k-1-j, D)
        Aj = []
        for i in range(p):
            Aj.append((a_j * pow(2, i, D)) % D)
        A.append(Aj)
        print(f"  A_{j} (weight 3^{k-1-j} = {3**(k-1-j)}): {Aj[:8]}...")

    # The achievable set is {sum of one element from each A_j, positions distinct}
    # The "distinct positions" constraint is crucial!
    # Without it, we'd be computing the full sumset A_0 + A_1 + ... + A_{k-1}

    # Let's check: what's the UNRESTRICTED sumset?
    # (Take any element from each A_j, allowing repeated positions)
    if D < 200:
        unrestricted = {0}
        for j in range(k):
            new = set()
            for s in unrestricted:
                for a in A[j]:
                    new.add((s + a) % D)
            unrestricted = new
        print(f"\n  Unrestricted sumset size: {len(unrestricted)}/{D}")
        print(f"  0 in unrestricted sumset: {0 in unrestricted}")

        # Now the restricted sumset (distinct positions)
        restricted = set()
        for I in combinations(range(p), k):
            s = S_value(I, k) % D
            restricted.add(s)
        print(f"  Restricted sumset size: {len(restricted)}/{D}")
        print(f"  0 in restricted sumset: {0 in restricted}")

        # Difference: which residues are in unrestricted but not restricted?
        diff = unrestricted - restricted
        print(f"  In unrestricted but not restricted: {len(diff)}")
        if len(diff) < 30:
            print(f"    Residues: {sorted(diff)}")
            print(f"    0 in this difference: {0 in diff}")

    # KEY OBSERVATION: If 0 is in the unrestricted sumset but NOT in the
    # restricted sumset, then the distinct-position constraint is what
    # prevents 0 from being achieved. This would mean the proof must
    # use the distinct-position structure, not just the weighted sum structure.

    # ALTERNATIVELY: if 0 is not even in the unrestricted sumset, then
    # the weighted sum structure alone prevents 0, and distinct-positions
    # is not needed. This would be a stronger result.


# Run analysis
for p, k_round in [(5, None), (7, None), (8, None), (10, None), (13, None)]:
    k = k_round or round(p * log(2) / log(3))
    if 0 < k < p and 2**p - 3**k > 0:
        analyze_residue_zero(p, k)

print("\n\n" + "#"*70)
print("SUMSET STRUCTURE")
print("#"*70)

for p in [5, 7, 8]:
    k = round(p * log(2) / log(3))
    if 0 < k < p and 2**p - 3**k > 0:
        analyze_sumset_structure(p, k)
